version: '3.8'
services:
  dev-db: 
    image: postgres:16.0
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: ecommerce_api
    networks:
      - ecommerce_api_network
networks:
  ecommerce_api_network:

